#!/usr/bin/env bash
#Display the content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

for file in * 
do
	echo "$file" | cut -d "-" -f2
done
