#!/usr/bin/env bash
#Information about the school files
#Check if the school file exists

if [ -e school ]; then
	echo "school file exists"

	#Check if the school file exists or not
	if [ -s school ]; then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	#Checkfor the regular file
	if [ -f school ]; then
		echo "school is a regular file"
	fi
#File does not exist
else 	
	echo "school file does not exist"
fi
