#!/usr/bin/env bash
# Displays a list of currently running processes
# it shows all processes, for all users, including those which might not have a TTY
# Displays in a user-oriented farmat
# Show process heirachy

ps auxf

